//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class AlertUserBuilder
    {
        #region Create Method
        public static AlertUser Create()
        {
            return new AlertUser
            {
    				Code = Guid.NewGuid(),
    				AlertCode = Guid.NewGuid(),
    				UserCode = Guid.NewGuid(),
    				UserMessageStatus = "test UserMessageStatus",
    				RowIdentifier = null,
    				AcknowledgedDate = DateTime.Now
            };
        }

        #endregion
    
        #region With Methods
       	public static AlertUser WithCode(this AlertUser alertUser, Guid code)
        {
            alertUser.Code = code;
            return alertUser;
        }
       	public static AlertUser WithAlertCode(this AlertUser alertUser, Guid alertCode)
        {
            alertUser.AlertCode = alertCode;
            return alertUser;
        }
       	public static AlertUser WithUserCode(this AlertUser alertUser, Guid userCode)
        {
            alertUser.UserCode = userCode;
            return alertUser;
        }
       	public static AlertUser WithUserMessageStatus(this AlertUser alertUser, String userMessageStatus)
        {
            alertUser.UserMessageStatus = userMessageStatus;
            return alertUser;
        }
       	public static AlertUser WithAcknowledgedDate(this AlertUser alertUser, DateTime acknowledgedDate)
        {
            alertUser.AcknowledgedDate = acknowledgedDate;
            return alertUser;
        }
       	public static AlertUser WithAlert(this AlertUser alertUser, Alert alert)
        {
            alertUser.Alert = alert;
            return alertUser;
        }
    
       	public static AlertUser WithUser(this AlertUser alertUser, MCUser user)
        {
            alertUser.User = user;
            return alertUser;
        }
    

        #endregion
    }
}
