//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class AlertBuilder
    {
        #region Create Method
        public static Alert Create()
        {
            return new Alert
            {
    				Code = Guid.NewGuid(),
    				Name = "test Name",
    				Type = "test Type",
    				TriggerTable = "test TriggerTable",
    				TriggerOperator = "test TriggerOperator",
    				TriggerValue = "test TriggerValue",
    				TriggerDateTime = DateTime.Now,
    				Status = "test Status",
    				Message = "test Message",
    				CreatedDate = DateTime.Now,
    				CreatedBy = "test CreatedBy",
    				RowIdentifier = null,
    				CompletedDate = DateTime.Now,
    				TriggerKeyField = "test TriggerKeyField",
    				TriggerKeyValue = "test TriggerKeyValue",
    				TriggerField = "test TriggerField",
    				RelatedEntityCode = Guid.NewGuid()
            };
        }

        #endregion
    
        #region With Methods
       	public static Alert WithCode(this Alert alert, Guid code)
        {
            alert.Code = code;
            return alert;
        }
       	public static Alert WithName(this Alert alert, String name)
        {
            alert.Name = name;
            return alert;
        }
       	public static Alert WithType(this Alert alert, String type)
        {
            alert.Type = type;
            return alert;
        }
       	public static Alert WithTriggerTable(this Alert alert, String triggerTable)
        {
            alert.TriggerTable = triggerTable;
            return alert;
        }
       	public static Alert WithTriggerOperator(this Alert alert, String triggerOperator)
        {
            alert.TriggerOperator = triggerOperator;
            return alert;
        }
       	public static Alert WithTriggerValue(this Alert alert, String triggerValue)
        {
            alert.TriggerValue = triggerValue;
            return alert;
        }
       	public static Alert WithTriggerDateTime(this Alert alert, DateTime triggerDateTime)
        {
            alert.TriggerDateTime = triggerDateTime;
            return alert;
        }
       	public static Alert WithStatus(this Alert alert, String status)
        {
            alert.Status = status;
            return alert;
        }
       	public static Alert WithMessage(this Alert alert, String message)
        {
            alert.Message = message;
            return alert;
        }
       	public static Alert WithCreatedDate(this Alert alert, DateTime createdDate)
        {
            alert.CreatedDate = createdDate;
            return alert;
        }
       	public static Alert WithCreatedBy(this Alert alert, String createdBy)
        {
            alert.CreatedBy = createdBy;
            return alert;
        }
       	public static Alert WithCompletedDate(this Alert alert, DateTime completedDate)
        {
            alert.CompletedDate = completedDate;
            return alert;
        }
       	public static Alert WithTriggerKeyField(this Alert alert, String triggerKeyField)
        {
            alert.TriggerKeyField = triggerKeyField;
            return alert;
        }
       	public static Alert WithTriggerKeyValue(this Alert alert, String triggerKeyValue)
        {
            alert.TriggerKeyValue = triggerKeyValue;
            return alert;
        }
       	public static Alert WithTriggerField(this Alert alert, String triggerField)
        {
            alert.TriggerField = triggerField;
            return alert;
        }
       	public static Alert WithRelatedEntityCode(this Alert alert, Guid relatedEntityCode)
        {
            alert.RelatedEntityCode = relatedEntityCode;
            return alert;
        }
       	public static Alert WithAlertUsers(this Alert alert, ICollection< AlertUser> alertUsers)
        {
            alert.AlertUsers = alertUsers;
            return alert;
        }
    

        #endregion
    }
}
