//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class CategoryLogBuilder
    {
        #region Create Method
        public static CategoryLog Create()
        {
            return new CategoryLog
            {
    				CategoryLogID = 100,
    				CategoryID = 100,
    				LogID = 100
            };
        }

        #endregion
    
        #region With Methods
       	public static CategoryLog WithCategoryLogID(this CategoryLog categoryLog, Int32 categoryLogID)
        {
            categoryLog.CategoryLogID = categoryLogID;
            return categoryLog;
        }
       	public static CategoryLog WithCategoryID(this CategoryLog categoryLog, Int32 categoryID)
        {
            categoryLog.CategoryID = categoryID;
            return categoryLog;
        }
       	public static CategoryLog WithLogID(this CategoryLog categoryLog, Int32 logID)
        {
            categoryLog.LogID = logID;
            return categoryLog;
        }
       	public static CategoryLog WithCategory(this CategoryLog categoryLog, Category category)
        {
            categoryLog.Category = category;
            return categoryLog;
        }
    
       	public static CategoryLog WithLog(this CategoryLog categoryLog, Log log)
        {
            categoryLog.Log = log;
            return categoryLog;
        }
    

        #endregion
    }
}
