//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class CategoryBuilder
    {
        #region Create Method
        public static Category Create()
        {
            return new Category
            {
    				CategoryID = 100,
    				CategoryName = "test CategoryName"
            };
        }

        #endregion
    
        #region With Methods
       	public static Category WithCategoryID(this Category category, Int32 categoryID)
        {
            category.CategoryID = categoryID;
            return category;
        }
       	public static Category WithCategoryName(this Category category, String categoryName)
        {
            category.CategoryName = categoryName;
            return category;
        }
       	public static Category WithCategoryLogs(this Category category, ICollection< CategoryLog> categoryLogs)
        {
            category.CategoryLogs = categoryLogs;
            return category;
        }
    

        #endregion
    }
}
