//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class DataItemBuilder
    {
        #region Create Method
        public static DataItem Create()
        {
            return new DataItem
            {
    				Code = Guid.NewGuid(),
    				Name = "test Name",
    				DataType = "test DataType",
    				Caption = "test Caption",
    				Description = "test Description",
    				IsGroup = false,
    				LocationOnSystem = "test LocationOnSystem",
    				IsValueType = false,
    				IsSummable = false,
    				IsCommonTableGrouping = false,
    				DataTableCode = Guid.NewGuid(),
    				DataCategoryCode = Guid.NewGuid(),
    				RowIdentifier = null,
    				IsLink = false,
    				LinkAssociatedField = "test LinkAssociatedField"
            };
        }

        #endregion
    
        #region With Methods
       	public static DataItem WithCode(this DataItem dataItem, Guid code)
        {
            dataItem.Code = code;
            return dataItem;
        }
       	public static DataItem WithName(this DataItem dataItem, String name)
        {
            dataItem.Name = name;
            return dataItem;
        }
       	public static DataItem WithDataType(this DataItem dataItem, String dataType)
        {
            dataItem.DataType = dataType;
            return dataItem;
        }
       	public static DataItem WithCaption(this DataItem dataItem, String caption)
        {
            dataItem.Caption = caption;
            return dataItem;
        }
       	public static DataItem WithDescription(this DataItem dataItem, String description)
        {
            dataItem.Description = description;
            return dataItem;
        }
       	public static DataItem WithIsGroup(this DataItem dataItem, Boolean isGroup)
        {
            dataItem.IsGroup = isGroup;
            return dataItem;
        }
       	public static DataItem WithLocationOnSystem(this DataItem dataItem, String locationOnSystem)
        {
            dataItem.LocationOnSystem = locationOnSystem;
            return dataItem;
        }
       	public static DataItem WithIsValueType(this DataItem dataItem, Boolean isValueType)
        {
            dataItem.IsValueType = isValueType;
            return dataItem;
        }
       	public static DataItem WithIsSummable(this DataItem dataItem, Boolean isSummable)
        {
            dataItem.IsSummable = isSummable;
            return dataItem;
        }
       	public static DataItem WithIsCommonTableGrouping(this DataItem dataItem, Boolean isCommonTableGrouping)
        {
            dataItem.IsCommonTableGrouping = isCommonTableGrouping;
            return dataItem;
        }
       	public static DataItem WithDataTableCode(this DataItem dataItem, Guid dataTableCode)
        {
            dataItem.DataTableCode = dataTableCode;
            return dataItem;
        }
       	public static DataItem WithDataCategoryCode(this DataItem dataItem, Guid dataCategoryCode)
        {
            dataItem.DataCategoryCode = dataCategoryCode;
            return dataItem;
        }
       	public static DataItem WithIsLink(this DataItem dataItem, Boolean isLink)
        {
            dataItem.IsLink = isLink;
            return dataItem;
        }
       	public static DataItem WithLinkAssociatedField(this DataItem dataItem, String linkAssociatedField)
        {
            dataItem.LinkAssociatedField = linkAssociatedField;
            return dataItem;
        }
       	public static DataItem WithDataCategory(this DataItem dataItem, DataCategory dataCategory)
        {
            dataItem.DataCategory = dataCategory;
            return dataItem;
        }
    
       	public static DataItem WithDataTable(this DataItem dataItem, DataTable dataTable)
        {
            dataItem.DataTable = dataTable;
            return dataItem;
        }
    
       	public static DataItem WithReportItems(this DataItem dataItem, ICollection< ReportItem> reportItems)
        {
            dataItem.ReportItems = reportItems;
            return dataItem;
        }
    

        #endregion
    }
}
