//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class DataTableBuilder
    {
        #region Create Method
        public static DataTable Create()
        {
            return new DataTable
            {
    				Code = Guid.NewGuid(),
    				Name = "test Name",
    				RowIdentifier = null,
    				DataModelCode = Guid.NewGuid(),
    				SchemaName = "test SchemaName"
            };
        }

        #endregion
    
        #region With Methods
       	public static DataTable WithCode(this DataTable dataTable, Guid code)
        {
            dataTable.Code = code;
            return dataTable;
        }
       	public static DataTable WithName(this DataTable dataTable, String name)
        {
            dataTable.Name = name;
            return dataTable;
        }
       	public static DataTable WithDataModelCode(this DataTable dataTable, Guid dataModelCode)
        {
            dataTable.DataModelCode = dataModelCode;
            return dataTable;
        }
       	public static DataTable WithSchemaName(this DataTable dataTable, String schemaName)
        {
            dataTable.SchemaName = schemaName;
            return dataTable;
        }
       	public static DataTable WithDataItems(this DataTable dataTable, ICollection< DataItem> dataItems)
        {
            dataTable.DataItems = dataItems;
            return dataTable;
        }
    
       	public static DataTable WithDataTableRelationships(this DataTable dataTable, ICollection< DataTableRelationship> dataTableRelationships)
        {
            dataTable.DataTableRelationships = dataTableRelationships;
            return dataTable;
        }
    
       	public static DataTable WithDataTableRelationships1(this DataTable dataTable, ICollection< DataTableRelationship> dataTableRelationships1)
        {
            dataTable.DataTableRelationships1 = dataTableRelationships1;
            return dataTable;
        }
    
       	public static DataTable WithDataModel(this DataTable dataTable, DataModel dataModel)
        {
            dataTable.DataModel = dataModel;
            return dataTable;
        }
    

        #endregion
    }
}
