//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class DataTableRelationshipBuilder
    {
        #region Create Method
        public static DataTableRelationship Create()
        {
            return new DataTableRelationship
            {
    				Code = Guid.NewGuid(),
    				JoinInfo = "test JoinInfo",
    				DataTableFromCode = Guid.NewGuid(),
    				DataTableToCode = Guid.NewGuid(),
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static DataTableRelationship WithCode(this DataTableRelationship dataTableRelationship, Guid code)
        {
            dataTableRelationship.Code = code;
            return dataTableRelationship;
        }
       	public static DataTableRelationship WithJoinInfo(this DataTableRelationship dataTableRelationship, String joinInfo)
        {
            dataTableRelationship.JoinInfo = joinInfo;
            return dataTableRelationship;
        }
       	public static DataTableRelationship WithDataTableFromCode(this DataTableRelationship dataTableRelationship, Guid dataTableFromCode)
        {
            dataTableRelationship.DataTableFromCode = dataTableFromCode;
            return dataTableRelationship;
        }
       	public static DataTableRelationship WithDataTableToCode(this DataTableRelationship dataTableRelationship, Guid dataTableToCode)
        {
            dataTableRelationship.DataTableToCode = dataTableToCode;
            return dataTableRelationship;
        }
       	public static DataTableRelationship WithDataTable(this DataTableRelationship dataTableRelationship, DataTable dataTable)
        {
            dataTableRelationship.DataTable = dataTable;
            return dataTableRelationship;
        }
    
       	public static DataTableRelationship WithDataTable1(this DataTableRelationship dataTableRelationship, DataTable dataTable1)
        {
            dataTableRelationship.DataTable1 = dataTable1;
            return dataTableRelationship;
        }
    
       	public static DataTableRelationship WithDataTableRelationshipJoins(this DataTableRelationship dataTableRelationship, ICollection< DataTableRelationshipJoin> dataTableRelationshipJoins)
        {
            dataTableRelationship.DataTableRelationshipJoins = dataTableRelationshipJoins;
            return dataTableRelationship;
        }
    

        #endregion
    }
}
