//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class DataCategoryBuilder
    {
        #region Create Method
        public static DataCategory Create()
        {
            return new DataCategory
            {
    				Code = Guid.NewGuid(),
    				Name = "test Name",
    				SortField = 100,
    				RowIdentifier = null,
    				DataModelCode = Guid.NewGuid()
            };
        }

        #endregion
    
        #region With Methods
       	public static DataCategory WithCode(this DataCategory dataCategory, Guid code)
        {
            dataCategory.Code = code;
            return dataCategory;
        }
       	public static DataCategory WithName(this DataCategory dataCategory, String name)
        {
            dataCategory.Name = name;
            return dataCategory;
        }
       	public static DataCategory WithSortField(this DataCategory dataCategory, Int32 sortField)
        {
            dataCategory.SortField = sortField;
            return dataCategory;
        }
       	public static DataCategory WithDataModelCode(this DataCategory dataCategory, Guid dataModelCode)
        {
            dataCategory.DataModelCode = dataModelCode;
            return dataCategory;
        }
       	public static DataCategory WithDataItems(this DataCategory dataCategory, ICollection< DataItem> dataItems)
        {
            dataCategory.DataItems = dataItems;
            return dataCategory;
        }
    
       	public static DataCategory WithDataModel(this DataCategory dataCategory, DataModel dataModel)
        {
            dataCategory.DataModel = dataModel;
            return dataCategory;
        }
    

        #endregion
    }
}
