//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class DataModelBuilder
    {
        #region Create Method
        public static DataModel Create()
        {
            return new DataModel
            {
    				Code = Guid.NewGuid(),
    				Name = "test Name",
    				Description = "test Description",
    				Rowidentifier = null,
    				DatasourceName = "test DatasourceName"
            };
        }

        #endregion
    
        #region With Methods
       	public static DataModel WithCode(this DataModel dataModel, Guid code)
        {
            dataModel.Code = code;
            return dataModel;
        }
       	public static DataModel WithName(this DataModel dataModel, String name)
        {
            dataModel.Name = name;
            return dataModel;
        }
       	public static DataModel WithDescription(this DataModel dataModel, String description)
        {
            dataModel.Description = description;
            return dataModel;
        }
       	public static DataModel WithDatasourceName(this DataModel dataModel, String datasourceName)
        {
            dataModel.DatasourceName = datasourceName;
            return dataModel;
        }
       	public static DataModel WithDataCategories(this DataModel dataModel, ICollection< DataCategory> dataCategories)
        {
            dataModel.DataCategories = dataCategories;
            return dataModel;
        }
    
       	public static DataModel WithDataTables(this DataModel dataModel, ICollection< DataTable> dataTables)
        {
            dataModel.DataTables = dataTables;
            return dataModel;
        }
    
       	public static DataModel WithDataTableJoins(this DataModel dataModel, ICollection< DataTableJoin> dataTableJoins)
        {
            dataModel.DataTableJoins = dataTableJoins;
            return dataModel;
        }
    
       	public static DataModel WithReports_1(this DataModel dataModel, ICollection< Report> reports_1)
        {
            dataModel.Reports_1 = reports_1;
            return dataModel;
        }
    

        #endregion
    }
}
