//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class DataTableRelationshipJoinBuilder
    {
        #region Create Method
        public static DataTableRelationshipJoin Create()
        {
            return new DataTableRelationshipJoin
            {
    				Code = Guid.NewGuid(),
    				DataTableRelationshipCode = Guid.NewGuid(),
    				DataTableJoinCode = Guid.NewGuid(),
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static DataTableRelationshipJoin WithCode(this DataTableRelationshipJoin dataTableRelationshipJoin, Guid code)
        {
            dataTableRelationshipJoin.Code = code;
            return dataTableRelationshipJoin;
        }
       	public static DataTableRelationshipJoin WithDataTableRelationshipCode(this DataTableRelationshipJoin dataTableRelationshipJoin, Guid dataTableRelationshipCode)
        {
            dataTableRelationshipJoin.DataTableRelationshipCode = dataTableRelationshipCode;
            return dataTableRelationshipJoin;
        }
       	public static DataTableRelationshipJoin WithDataTableJoinCode(this DataTableRelationshipJoin dataTableRelationshipJoin, Guid dataTableJoinCode)
        {
            dataTableRelationshipJoin.DataTableJoinCode = dataTableJoinCode;
            return dataTableRelationshipJoin;
        }
       	public static DataTableRelationshipJoin WithDataTableJoin(this DataTableRelationshipJoin dataTableRelationshipJoin, DataTableJoin dataTableJoin)
        {
            dataTableRelationshipJoin.DataTableJoin = dataTableJoin;
            return dataTableRelationshipJoin;
        }
    
       	public static DataTableRelationshipJoin WithDataTableRelationship(this DataTableRelationshipJoin dataTableRelationshipJoin, DataTableRelationship dataTableRelationship)
        {
            dataTableRelationshipJoin.DataTableRelationship = dataTableRelationship;
            return dataTableRelationshipJoin;
        }
    

        #endregion
    }
}
