//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class FilterBuilder
    {
        #region Create Method
        public static Filter Create()
        {
            return new Filter
            {
    				Code = Guid.NewGuid(),
    				Operand = "test Operand",
    				FilterValue = "test FilterValue",
    				ReportItemCode = Guid.NewGuid(),
    				SortField = 100,
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static Filter WithCode(this Filter filter, Guid code)
        {
            filter.Code = code;
            return filter;
        }
       	public static Filter WithOperand(this Filter filter, String operand)
        {
            filter.Operand = operand;
            return filter;
        }
       	public static Filter WithFilterValue(this Filter filter, String filterValue)
        {
            filter.FilterValue = filterValue;
            return filter;
        }
       	public static Filter WithReportItemCode(this Filter filter, Guid reportItemCode)
        {
            filter.ReportItemCode = reportItemCode;
            return filter;
        }
       	public static Filter WithSortField(this Filter filter, Int32 sortField)
        {
            filter.SortField = sortField;
            return filter;
        }
       	public static Filter WithReportItem(this Filter filter, ReportItem reportItem)
        {
            filter.ReportItem = reportItem;
            return filter;
        }
    

        #endregion
    }
}
