//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class InputFileHistoryBuilder
    {
        #region Create Method
        public static InputFileHistory Create()
        {
            return new InputFileHistory
            {
    				Code = Guid.NewGuid(),
    				FileType = "test FileType",
    				Filename = "test Filename",
    				TransferDate = DateTime.Now,
    				ProviderOrganisationKeyValue = "test ProviderOrganisationKeyValue",
    				Status = "test Status",
    				LoadedBy = "test LoadedBy",
    				LoadedDate = DateTime.Now,
    				ValidatedLoadDate = DateTime.Now,
    				UploadDecision = 100,
    				NumberOfRecords = 100,
    				NumberOfValidRecords = 100,
    				NumberOfErrorRecords = 100,
    				NumberOfWarningRecords = 100,
    				NumberOfInformationalRecords = 100,
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static InputFileHistory WithCode(this InputFileHistory inputFileHistory, Guid code)
        {
            inputFileHistory.Code = code;
            return inputFileHistory;
        }
       	public static InputFileHistory WithFileType(this InputFileHistory inputFileHistory, String fileType)
        {
            inputFileHistory.FileType = fileType;
            return inputFileHistory;
        }
       	public static InputFileHistory WithFilename(this InputFileHistory inputFileHistory, String filename)
        {
            inputFileHistory.Filename = filename;
            return inputFileHistory;
        }
       	public static InputFileHistory WithTransferDate(this InputFileHistory inputFileHistory, DateTime transferDate)
        {
            inputFileHistory.TransferDate = transferDate;
            return inputFileHistory;
        }
       	public static InputFileHistory WithProviderOrganisationKeyValue(this InputFileHistory inputFileHistory, String providerOrganisationKeyValue)
        {
            inputFileHistory.ProviderOrganisationKeyValue = providerOrganisationKeyValue;
            return inputFileHistory;
        }
       	public static InputFileHistory WithStatus(this InputFileHistory inputFileHistory, String status)
        {
            inputFileHistory.Status = status;
            return inputFileHistory;
        }
       	public static InputFileHistory WithLoadedBy(this InputFileHistory inputFileHistory, String loadedBy)
        {
            inputFileHistory.LoadedBy = loadedBy;
            return inputFileHistory;
        }
       	public static InputFileHistory WithLoadedDate(this InputFileHistory inputFileHistory, DateTime loadedDate)
        {
            inputFileHistory.LoadedDate = loadedDate;
            return inputFileHistory;
        }
       	public static InputFileHistory WithValidatedLoadDate(this InputFileHistory inputFileHistory, DateTime validatedLoadDate)
        {
            inputFileHistory.ValidatedLoadDate = validatedLoadDate;
            return inputFileHistory;
        }
       	public static InputFileHistory WithUploadDecision(this InputFileHistory inputFileHistory, Int32 uploadDecision)
        {
            inputFileHistory.UploadDecision = uploadDecision;
            return inputFileHistory;
        }
       	public static InputFileHistory WithNumberOfRecords(this InputFileHistory inputFileHistory, Int32 numberOfRecords)
        {
            inputFileHistory.NumberOfRecords = numberOfRecords;
            return inputFileHistory;
        }
       	public static InputFileHistory WithNumberOfValidRecords(this InputFileHistory inputFileHistory, Int32 numberOfValidRecords)
        {
            inputFileHistory.NumberOfValidRecords = numberOfValidRecords;
            return inputFileHistory;
        }
       	public static InputFileHistory WithNumberOfErrorRecords(this InputFileHistory inputFileHistory, Int32 numberOfErrorRecords)
        {
            inputFileHistory.NumberOfErrorRecords = numberOfErrorRecords;
            return inputFileHistory;
        }
       	public static InputFileHistory WithNumberOfWarningRecords(this InputFileHistory inputFileHistory, Int32 numberOfWarningRecords)
        {
            inputFileHistory.NumberOfWarningRecords = numberOfWarningRecords;
            return inputFileHistory;
        }
       	public static InputFileHistory WithNumberOfInformationalRecords(this InputFileHistory inputFileHistory, Int32 numberOfInformationalRecords)
        {
            inputFileHistory.NumberOfInformationalRecords = numberOfInformationalRecords;
            return inputFileHistory;
        }
       	public static InputFileHistory WithInputFileErrors(this InputFileHistory inputFileHistory, ICollection< InputFileError> inputFileErrors)
        {
            inputFileHistory.InputFileErrors = inputFileErrors;
            return inputFileHistory;
        }
    
       	public static InputFileHistory WithProviderOrganisations(this InputFileHistory inputFileHistory, ICollection< ProviderOrganisation> providerOrganisations)
        {
            inputFileHistory.ProviderOrganisations = providerOrganisations;
            return inputFileHistory;
        }
    
       	public static InputFileHistory WithUploadMonitors(this InputFileHistory inputFileHistory, ICollection< UploadMonitor> uploadMonitors)
        {
            inputFileHistory.UploadMonitors = uploadMonitors;
            return inputFileHistory;
        }
    

        #endregion
    }
}
