//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class JobStepBuilder
    {
        #region Create Method
        public static JobStep Create()
        {
            return new JobStep
            {
    				Code = Guid.NewGuid(),
    				Name = "test Name",
    				Description = "test Description",
    				StartTime = DateTime.Now,
    				EndTime = DateTime.Now,
    				Status = "test Status",
    				Category = "test Category",
    				LogText = "test LogText",
    				UploadJobQueueCode = Guid.NewGuid(),
    				StepOrder = 100
            };
        }

        #endregion
    
        #region With Methods
       	public static JobStep WithCode(this JobStep jobStep, Guid code)
        {
            jobStep.Code = code;
            return jobStep;
        }
       	public static JobStep WithName(this JobStep jobStep, String name)
        {
            jobStep.Name = name;
            return jobStep;
        }
       	public static JobStep WithDescription(this JobStep jobStep, String description)
        {
            jobStep.Description = description;
            return jobStep;
        }
       	public static JobStep WithStartTime(this JobStep jobStep, DateTime startTime)
        {
            jobStep.StartTime = startTime;
            return jobStep;
        }
       	public static JobStep WithEndTime(this JobStep jobStep, DateTime endTime)
        {
            jobStep.EndTime = endTime;
            return jobStep;
        }
       	public static JobStep WithStatus(this JobStep jobStep, String status)
        {
            jobStep.Status = status;
            return jobStep;
        }
       	public static JobStep WithCategory(this JobStep jobStep, String category)
        {
            jobStep.Category = category;
            return jobStep;
        }
       	public static JobStep WithLogText(this JobStep jobStep, String logText)
        {
            jobStep.LogText = logText;
            return jobStep;
        }
       	public static JobStep WithUploadJobQueueCode(this JobStep jobStep, Guid uploadJobQueueCode)
        {
            jobStep.UploadJobQueueCode = uploadJobQueueCode;
            return jobStep;
        }
       	public static JobStep WithStepOrder(this JobStep jobStep, Int32 stepOrder)
        {
            jobStep.StepOrder = stepOrder;
            return jobStep;
        }
       	public static JobStep WithUploadJobQueue(this JobStep jobStep, UploadJobQueue uploadJobQueue)
        {
            jobStep.UploadJobQueue = uploadJobQueue;
            return jobStep;
        }
    

        #endregion
    }
}
