//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class LogBuilder
    {
        #region Create Method
        public static Log Create()
        {
            return new Log
            {
    				LogID = 100,
    				EventID = 100,
    				Priority = 100,
    				Severity = "test Severity",
    				Title = "test Title",
    				Timestamp = DateTime.Now,
    				MachineName = "test MachineName",
    				AppDomainName = "test AppDomainName",
    				ProcessID = "test ProcessID",
    				ProcessName = "test ProcessName",
    				ThreadName = "test ThreadName",
    				Win32ThreadId = "test Win32ThreadId",
    				Message = "test Message",
    				FormattedMessage = "test FormattedMessage"
            };
        }

        #endregion
    
        #region With Methods
       	public static Log WithLogID(this Log log, Int32 logID)
        {
            log.LogID = logID;
            return log;
        }
       	public static Log WithEventID(this Log log, Int32 eventID)
        {
            log.EventID = eventID;
            return log;
        }
       	public static Log WithPriority(this Log log, Int32 priority)
        {
            log.Priority = priority;
            return log;
        }
       	public static Log WithSeverity(this Log log, String severity)
        {
            log.Severity = severity;
            return log;
        }
       	public static Log WithTitle(this Log log, String title)
        {
            log.Title = title;
            return log;
        }
       	public static Log WithTimestamp(this Log log, DateTime timestamp)
        {
            log.Timestamp = timestamp;
            return log;
        }
       	public static Log WithMachineName(this Log log, String machineName)
        {
            log.MachineName = machineName;
            return log;
        }
       	public static Log WithAppDomainName(this Log log, String appDomainName)
        {
            log.AppDomainName = appDomainName;
            return log;
        }
       	public static Log WithProcessID(this Log log, String processID)
        {
            log.ProcessID = processID;
            return log;
        }
       	public static Log WithProcessName(this Log log, String processName)
        {
            log.ProcessName = processName;
            return log;
        }
       	public static Log WithThreadName(this Log log, String threadName)
        {
            log.ThreadName = threadName;
            return log;
        }
       	public static Log WithWin32ThreadId(this Log log, String win32ThreadId)
        {
            log.Win32ThreadId = win32ThreadId;
            return log;
        }
       	public static Log WithMessage(this Log log, String message)
        {
            log.Message = message;
            return log;
        }
       	public static Log WithFormattedMessage(this Log log, String formattedMessage)
        {
            log.FormattedMessage = formattedMessage;
            return log;
        }
       	public static Log WithCategoryLogs(this Log log, ICollection< CategoryLog> categoryLogs)
        {
            log.CategoryLogs = categoryLogs;
            return log;
        }
    

        #endregion
    }
}
