//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class MCRoleBuilder
    {
        #region Create Method
        public static MCRole Create()
        {
            return new MCRole
            {
    				Code = Guid.NewGuid(),
    				Name = "test Name",
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static MCRole WithCode(this MCRole mCRole, Guid code)
        {
            mCRole.Code = code;
            return mCRole;
        }
       	public static MCRole WithName(this MCRole mCRole, String name)
        {
            mCRole.Name = name;
            return mCRole;
        }
       	public static MCRole WithUserRoles(this MCRole mCRole, ICollection< MCUserRole> userRoles)
        {
            mCRole.UserRoles = userRoles;
            return mCRole;
        }
    

        #endregion
    }
}
