//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class MCSystemParameterBuilder
    {
        #region Create Method
        public static MCSystemParameter Create()
        {
            return new MCSystemParameter
            {
    				Code = Guid.NewGuid(),
    				Name = "test Name",
    				LongName = "test LongName",
    				Description = "test Description",
    				ParameterValue = "test ParameterValue",
    				Secure = false,
    				BusinessData = "test BusinessData",
    				DateUpdated = DateTime.Now,
    				LastUpdatedUserCode = Guid.NewGuid(),
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static MCSystemParameter WithCode(this MCSystemParameter mCSystemParameter, Guid code)
        {
            mCSystemParameter.Code = code;
            return mCSystemParameter;
        }
       	public static MCSystemParameter WithName(this MCSystemParameter mCSystemParameter, String name)
        {
            mCSystemParameter.Name = name;
            return mCSystemParameter;
        }
       	public static MCSystemParameter WithLongName(this MCSystemParameter mCSystemParameter, String longName)
        {
            mCSystemParameter.LongName = longName;
            return mCSystemParameter;
        }
       	public static MCSystemParameter WithDescription(this MCSystemParameter mCSystemParameter, String description)
        {
            mCSystemParameter.Description = description;
            return mCSystemParameter;
        }
       	public static MCSystemParameter WithParameterValue(this MCSystemParameter mCSystemParameter, String parameterValue)
        {
            mCSystemParameter.ParameterValue = parameterValue;
            return mCSystemParameter;
        }
       	public static MCSystemParameter WithSecure(this MCSystemParameter mCSystemParameter, Boolean secure)
        {
            mCSystemParameter.Secure = secure;
            return mCSystemParameter;
        }
       	public static MCSystemParameter WithBusinessData(this MCSystemParameter mCSystemParameter, String businessData)
        {
            mCSystemParameter.BusinessData = businessData;
            return mCSystemParameter;
        }
       	public static MCSystemParameter WithDateUpdated(this MCSystemParameter mCSystemParameter, DateTime dateUpdated)
        {
            mCSystemParameter.DateUpdated = dateUpdated;
            return mCSystemParameter;
        }
       	public static MCSystemParameter WithLastUpdatedUserCode(this MCSystemParameter mCSystemParameter, Guid lastUpdatedUserCode)
        {
            mCSystemParameter.LastUpdatedUserCode = lastUpdatedUserCode;
            return mCSystemParameter;
        }

        #endregion
    }
}
