//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class MCUserBuilder
    {
        #region Create Method
        public static MCUser Create()
        {
            return new MCUser
            {
    				Code = Guid.NewGuid(),
    				Name = "test Name",
    				Forename = "test Forename",
    				Surname = "test Surname",
    				Email = "test Email",
    				Password = "test Password",
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static MCUser WithCode(this MCUser mCUser, Guid code)
        {
            mCUser.Code = code;
            return mCUser;
        }
       	public static MCUser WithName(this MCUser mCUser, String name)
        {
            mCUser.Name = name;
            return mCUser;
        }
       	public static MCUser WithForename(this MCUser mCUser, String forename)
        {
            mCUser.Forename = forename;
            return mCUser;
        }
       	public static MCUser WithSurname(this MCUser mCUser, String surname)
        {
            mCUser.Surname = surname;
            return mCUser;
        }
       	public static MCUser WithEmail(this MCUser mCUser, String email)
        {
            mCUser.Email = email;
            return mCUser;
        }
       	public static MCUser WithPassword(this MCUser mCUser, String password)
        {
            mCUser.Password = password;
            return mCUser;
        }
       	public static MCUser WithUserRoles(this MCUser mCUser, ICollection< MCUserRole> userRoles)
        {
            mCUser.UserRoles = userRoles;
            return mCUser;
        }
    
       	public static MCUser WithUserReportGroups(this MCUser mCUser, ICollection< UserReportGroup> userReportGroups)
        {
            mCUser.UserReportGroups = userReportGroups;
            return mCUser;
        }
    
       	public static MCUser WithAlertUsers(this MCUser mCUser, ICollection< AlertUser> alertUsers)
        {
            mCUser.AlertUsers = alertUsers;
            return mCUser;
        }
    

        #endregion
    }
}
