//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class MCUserRoleBuilder
    {
        #region Create Method
        public static MCUserRole Create()
        {
            return new MCUserRole
            {
    				Code = Guid.NewGuid(),
    				UserCode = Guid.NewGuid(),
    				RoleCode = Guid.NewGuid(),
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static MCUserRole WithCode(this MCUserRole mCUserRole, Guid code)
        {
            mCUserRole.Code = code;
            return mCUserRole;
        }
       	public static MCUserRole WithUserCode(this MCUserRole mCUserRole, Guid userCode)
        {
            mCUserRole.UserCode = userCode;
            return mCUserRole;
        }
       	public static MCUserRole WithRoleCode(this MCUserRole mCUserRole, Guid roleCode)
        {
            mCUserRole.RoleCode = roleCode;
            return mCUserRole;
        }
       	public static MCUserRole WithRole(this MCUserRole mCUserRole, MCRole role)
        {
            mCUserRole.Role = role;
            return mCUserRole;
        }
    
       	public static MCUserRole WithUser(this MCUserRole mCUserRole, MCUser user)
        {
            mCUserRole.User = user;
            return mCUserRole;
        }
    

        #endregion
    }
}
