//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class ProviderOrganisationBuilder
    {
        #region Create Method
        public static ProviderOrganisation Create()
        {
            return new ProviderOrganisation
            {
    				Code = Guid.NewGuid(),
    				ID = 100,
    				RegionID = "test RegionID",
    				KeyValue = "test KeyValue",
    				FileType = "test FileType",
    				Name = "test Name",
    				Status = "test Status",
    				CurrentValidatedFileCode = Guid.NewGuid(),
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static ProviderOrganisation WithCode(this ProviderOrganisation providerOrganisation, Guid code)
        {
            providerOrganisation.Code = code;
            return providerOrganisation;
        }
       	public static ProviderOrganisation WithID(this ProviderOrganisation providerOrganisation, Int32 iD)
        {
            providerOrganisation.ID = iD;
            return providerOrganisation;
        }
       	public static ProviderOrganisation WithRegionID(this ProviderOrganisation providerOrganisation, String regionID)
        {
            providerOrganisation.RegionID = regionID;
            return providerOrganisation;
        }
       	public static ProviderOrganisation WithKeyValue(this ProviderOrganisation providerOrganisation, String keyValue)
        {
            providerOrganisation.KeyValue = keyValue;
            return providerOrganisation;
        }
       	public static ProviderOrganisation WithFileType(this ProviderOrganisation providerOrganisation, String fileType)
        {
            providerOrganisation.FileType = fileType;
            return providerOrganisation;
        }
       	public static ProviderOrganisation WithName(this ProviderOrganisation providerOrganisation, String name)
        {
            providerOrganisation.Name = name;
            return providerOrganisation;
        }
       	public static ProviderOrganisation WithStatus(this ProviderOrganisation providerOrganisation, String status)
        {
            providerOrganisation.Status = status;
            return providerOrganisation;
        }
       	public static ProviderOrganisation WithCurrentValidatedFileCode(this ProviderOrganisation providerOrganisation, Guid currentValidatedFileCode)
        {
            providerOrganisation.CurrentValidatedFileCode = currentValidatedFileCode;
            return providerOrganisation;
        }
       	public static ProviderOrganisation WithInputFileHistory(this ProviderOrganisation providerOrganisation, InputFileHistory inputFileHistory)
        {
            providerOrganisation.InputFileHistory = inputFileHistory;
            return providerOrganisation;
        }
    

        #endregion
    }
}
