//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class ReportGroupBuilder
    {
        #region Create Method
        public static ReportGroup Create()
        {
            return new ReportGroup
            {
    				Code = Guid.NewGuid(),
    				Name = "test Name",
    				ParentCode = Guid.NewGuid(),
    				ParentPath = "test ParentPath",
    				PathName = "test PathName",
    				ReportType = "test ReportType",
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static ReportGroup WithCode(this ReportGroup reportGroup, Guid code)
        {
            reportGroup.Code = code;
            return reportGroup;
        }
       	public static ReportGroup WithName(this ReportGroup reportGroup, String name)
        {
            reportGroup.Name = name;
            return reportGroup;
        }
       	public static ReportGroup WithParentCode(this ReportGroup reportGroup, Guid parentCode)
        {
            reportGroup.ParentCode = parentCode;
            return reportGroup;
        }
       	public static ReportGroup WithParentPath(this ReportGroup reportGroup, String parentPath)
        {
            reportGroup.ParentPath = parentPath;
            return reportGroup;
        }
       	public static ReportGroup WithPathName(this ReportGroup reportGroup, String pathName)
        {
            reportGroup.PathName = pathName;
            return reportGroup;
        }
       	public static ReportGroup WithReportType(this ReportGroup reportGroup, String reportType)
        {
            reportGroup.ReportType = reportType;
            return reportGroup;
        }
       	public static ReportGroup WithReports(this ReportGroup reportGroup, ICollection< Report> reports)
        {
            reportGroup.Reports = reports;
            return reportGroup;
        }
    
       	public static ReportGroup WithReportGroup1(this ReportGroup reportGroup, ICollection< ReportGroup> reportGroup1)
        {
            reportGroup.ReportGroup1 = reportGroup1;
            return reportGroup;
        }
    
       	public static ReportGroup WithReportGroup2(this ReportGroup reportGroup, ReportGroup reportGroup2)
        {
            reportGroup.ReportGroup2 = reportGroup2;
            return reportGroup;
        }
    
       	public static ReportGroup WithUserReportGroups(this ReportGroup reportGroup, ICollection< UserReportGroup> userReportGroups)
        {
            reportGroup.UserReportGroups = userReportGroups;
            return reportGroup;
        }
    

        #endregion
    }
}
