//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class ReportDataTableJoinBuilder
    {
        #region Create Method
        public static ReportDataTableJoin Create()
        {
            return new ReportDataTableJoin
            {
    				Code = Guid.NewGuid(),
    				JoinType = "test JoinType",
    				ReportCode = Guid.NewGuid(),
    				DataTableJoinCode = Guid.NewGuid(),
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static ReportDataTableJoin WithCode(this ReportDataTableJoin reportDataTableJoin, Guid code)
        {
            reportDataTableJoin.Code = code;
            return reportDataTableJoin;
        }
       	public static ReportDataTableJoin WithJoinType(this ReportDataTableJoin reportDataTableJoin, String joinType)
        {
            reportDataTableJoin.JoinType = joinType;
            return reportDataTableJoin;
        }
       	public static ReportDataTableJoin WithReportCode(this ReportDataTableJoin reportDataTableJoin, Guid reportCode)
        {
            reportDataTableJoin.ReportCode = reportCode;
            return reportDataTableJoin;
        }
       	public static ReportDataTableJoin WithDataTableJoinCode(this ReportDataTableJoin reportDataTableJoin, Guid dataTableJoinCode)
        {
            reportDataTableJoin.DataTableJoinCode = dataTableJoinCode;
            return reportDataTableJoin;
        }
       	public static ReportDataTableJoin WithDataTableJoin(this ReportDataTableJoin reportDataTableJoin, DataTableJoin dataTableJoin)
        {
            reportDataTableJoin.DataTableJoin = dataTableJoin;
            return reportDataTableJoin;
        }
    
       	public static ReportDataTableJoin WithReport(this ReportDataTableJoin reportDataTableJoin, Report report)
        {
            reportDataTableJoin.Report = report;
            return reportDataTableJoin;
        }
    

        #endregion
    }
}
