//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class ReportDBBuilder
    {
        #region Create Method
        public static ReportDB Create()
        {
            return new ReportDB
            {
    				ReportDBKey = 100,
    				ReportDBStatus = "test ReportDBStatus",
    				ReportDBLastLoadStarted = DateTime.Now,
    				ReportDBLastLoadFinished = DateTime.Now,
    				ReportDBLoadCounter = 100,
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static ReportDB WithReportDBKey(this ReportDB reportDB, Int32 reportDBKey)
        {
            reportDB.ReportDBKey = reportDBKey;
            return reportDB;
        }
       	public static ReportDB WithReportDBStatus(this ReportDB reportDB, String reportDBStatus)
        {
            reportDB.ReportDBStatus = reportDBStatus;
            return reportDB;
        }
       	public static ReportDB WithReportDBLastLoadStarted(this ReportDB reportDB, DateTime reportDBLastLoadStarted)
        {
            reportDB.ReportDBLastLoadStarted = reportDBLastLoadStarted;
            return reportDB;
        }
       	public static ReportDB WithReportDBLastLoadFinished(this ReportDB reportDB, DateTime reportDBLastLoadFinished)
        {
            reportDB.ReportDBLastLoadFinished = reportDBLastLoadFinished;
            return reportDB;
        }
       	public static ReportDB WithReportDBLoadCounter(this ReportDB reportDB, Int32 reportDBLoadCounter)
        {
            reportDB.ReportDBLoadCounter = reportDBLoadCounter;
            return reportDB;
        }

        #endregion
    }
}
