//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class ReportChartBuilder
    {
        #region Create Method
        public static ReportChart Create()
        {
            return new ReportChart
            {
    				Code = Guid.NewGuid(),
    				Title = "test Title",
    				ReportCode = Guid.NewGuid(),
    				CategoryReportItemCode = Guid.NewGuid(),
    				ChartStyle = "test ChartStyle",
    				Description = "test Description",
    				ChartType = "test ChartType",
    				RowIdentifier = null,
    				SortOrder = 100
            };
        }

        #endregion
    
        #region With Methods
       	public static ReportChart WithCode(this ReportChart reportChart, Guid code)
        {
            reportChart.Code = code;
            return reportChart;
        }
       	public static ReportChart WithTitle(this ReportChart reportChart, String title)
        {
            reportChart.Title = title;
            return reportChart;
        }
       	public static ReportChart WithReportCode(this ReportChart reportChart, Guid reportCode)
        {
            reportChart.ReportCode = reportCode;
            return reportChart;
        }
       	public static ReportChart WithCategoryReportItemCode(this ReportChart reportChart, Guid categoryReportItemCode)
        {
            reportChart.CategoryReportItemCode = categoryReportItemCode;
            return reportChart;
        }
       	public static ReportChart WithChartStyle(this ReportChart reportChart, String chartStyle)
        {
            reportChart.ChartStyle = chartStyle;
            return reportChart;
        }
       	public static ReportChart WithDescription(this ReportChart reportChart, String description)
        {
            reportChart.Description = description;
            return reportChart;
        }
       	public static ReportChart WithChartType(this ReportChart reportChart, String chartType)
        {
            reportChart.ChartType = chartType;
            return reportChart;
        }
       	public static ReportChart WithSortOrder(this ReportChart reportChart, Int32 sortOrder)
        {
            reportChart.SortOrder = sortOrder;
            return reportChart;
        }
       	public static ReportChart WithReport(this ReportChart reportChart, Report report)
        {
            reportChart.Report = report;
            return reportChart;
        }
    
       	public static ReportChart WithReportItem(this ReportChart reportChart, ReportItem reportItem)
        {
            reportChart.ReportItem = reportItem;
            return reportChart;
        }
    
       	public static ReportChart WithReportChartSeries(this ReportChart reportChart, ICollection< ReportChartSery> reportChartSeries)
        {
            reportChart.ReportChartSeries = reportChartSeries;
            return reportChart;
        }
    

        #endregion
    }
}
