//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class ReportChartSeryBuilder
    {
        #region Create Method
        public static ReportChartSery Create()
        {
            return new ReportChartSery
            {
    				Code = Guid.NewGuid(),
    				ReportChartCode = Guid.NewGuid(),
    				SeriesReportItemCode = Guid.NewGuid(),
    				RowIdentifier = null,
    				SortOrder = 100
            };
        }

        #endregion
    
        #region With Methods
       	public static ReportChartSery WithCode(this ReportChartSery reportChartSery, Guid code)
        {
            reportChartSery.Code = code;
            return reportChartSery;
        }
       	public static ReportChartSery WithReportChartCode(this ReportChartSery reportChartSery, Guid reportChartCode)
        {
            reportChartSery.ReportChartCode = reportChartCode;
            return reportChartSery;
        }
       	public static ReportChartSery WithSeriesReportItemCode(this ReportChartSery reportChartSery, Guid seriesReportItemCode)
        {
            reportChartSery.SeriesReportItemCode = seriesReportItemCode;
            return reportChartSery;
        }
       	public static ReportChartSery WithSortOrder(this ReportChartSery reportChartSery, Int32 sortOrder)
        {
            reportChartSery.SortOrder = sortOrder;
            return reportChartSery;
        }
       	public static ReportChartSery WithReportChart(this ReportChartSery reportChartSery, ReportChart reportChart)
        {
            reportChartSery.ReportChart = reportChart;
            return reportChartSery;
        }
    
       	public static ReportChartSery WithReportItem(this ReportChartSery reportChartSery, ReportItem reportItem)
        {
            reportChartSery.ReportItem = reportItem;
            return reportChartSery;
        }
    

        #endregion
    }
}
