//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class UploadMonitorBuilder
    {
        #region Create Method
        public static UploadMonitor Create()
        {
            return new UploadMonitor
            {
    				Code = Guid.NewGuid(),
    				Position = 100,
    				InputFileCode = Guid.NewGuid(),
    				TimeOccured = DateTime.Now,
    				StepDescription = "test StepDescription",
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static UploadMonitor WithCode(this UploadMonitor uploadMonitor, Guid code)
        {
            uploadMonitor.Code = code;
            return uploadMonitor;
        }
       	public static UploadMonitor WithPosition(this UploadMonitor uploadMonitor, Int32 position)
        {
            uploadMonitor.Position = position;
            return uploadMonitor;
        }
       	public static UploadMonitor WithInputFileCode(this UploadMonitor uploadMonitor, Guid inputFileCode)
        {
            uploadMonitor.InputFileCode = inputFileCode;
            return uploadMonitor;
        }
       	public static UploadMonitor WithTimeOccured(this UploadMonitor uploadMonitor, DateTime timeOccured)
        {
            uploadMonitor.TimeOccured = timeOccured;
            return uploadMonitor;
        }
       	public static UploadMonitor WithStepDescription(this UploadMonitor uploadMonitor, String stepDescription)
        {
            uploadMonitor.StepDescription = stepDescription;
            return uploadMonitor;
        }
       	public static UploadMonitor WithInputFileHistory(this UploadMonitor uploadMonitor, InputFileHistory inputFileHistory)
        {
            uploadMonitor.InputFileHistory = inputFileHistory;
            return uploadMonitor;
        }
    

        #endregion
    }
}
