//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class UploadJobQueueBuilder
    {
        #region Create Method
        public static UploadJobQueue Create()
        {
            return new UploadJobQueue
            {
    				Code = Guid.NewGuid(),
    				Position = 100,
    				Status = "test Status",
    				TimeAdded = DateTime.Now,
    				TimeStarted = DateTime.Now,
    				JobDescription = "test JobDescription",
    				UserId = "test UserId",
    				RowIdentifier = null,
    				EndTime = DateTime.Now,
    				JobData = "test JobData"
            };
        }

        #endregion
    
        #region With Methods
       	public static UploadJobQueue WithCode(this UploadJobQueue uploadJobQueue, Guid code)
        {
            uploadJobQueue.Code = code;
            return uploadJobQueue;
        }
       	public static UploadJobQueue WithPosition(this UploadJobQueue uploadJobQueue, Int32 position)
        {
            uploadJobQueue.Position = position;
            return uploadJobQueue;
        }
       	public static UploadJobQueue WithStatus(this UploadJobQueue uploadJobQueue, String status)
        {
            uploadJobQueue.Status = status;
            return uploadJobQueue;
        }
       	public static UploadJobQueue WithTimeAdded(this UploadJobQueue uploadJobQueue, DateTime timeAdded)
        {
            uploadJobQueue.TimeAdded = timeAdded;
            return uploadJobQueue;
        }
       	public static UploadJobQueue WithTimeStarted(this UploadJobQueue uploadJobQueue, DateTime timeStarted)
        {
            uploadJobQueue.TimeStarted = timeStarted;
            return uploadJobQueue;
        }
       	public static UploadJobQueue WithJobDescription(this UploadJobQueue uploadJobQueue, String jobDescription)
        {
            uploadJobQueue.JobDescription = jobDescription;
            return uploadJobQueue;
        }
       	public static UploadJobQueue WithUserId(this UploadJobQueue uploadJobQueue, String userId)
        {
            uploadJobQueue.UserId = userId;
            return uploadJobQueue;
        }
       	public static UploadJobQueue WithEndTime(this UploadJobQueue uploadJobQueue, DateTime endTime)
        {
            uploadJobQueue.EndTime = endTime;
            return uploadJobQueue;
        }
       	public static UploadJobQueue WithJobData(this UploadJobQueue uploadJobQueue, String jobData)
        {
            uploadJobQueue.JobData = jobData;
            return uploadJobQueue;
        }
       	public static UploadJobQueue WithJobSteps(this UploadJobQueue uploadJobQueue, ICollection< JobStep> jobSteps)
        {
            uploadJobQueue.JobSteps = jobSteps;
            return uploadJobQueue;
        }
    

        #endregion
    }
}
