//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using UcbManagementInformation.Server.DataAccess;

namespace UcbManagementInformation.Server.UnitTest.TestEntityBuilder
{
    public static partial class UserReportGroupBuilder
    {
        #region Create Method
        public static UserReportGroup Create()
        {
            return new UserReportGroup
            {
    				Code = Guid.NewGuid(),
    				UserCode = Guid.NewGuid(),
    				ReportGroupCode = Guid.NewGuid(),
    				AccessLevel = 100,
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static UserReportGroup WithCode(this UserReportGroup userReportGroup, Guid code)
        {
            userReportGroup.Code = code;
            return userReportGroup;
        }
       	public static UserReportGroup WithUserCode(this UserReportGroup userReportGroup, Guid userCode)
        {
            userReportGroup.UserCode = userCode;
            return userReportGroup;
        }
       	public static UserReportGroup WithReportGroupCode(this UserReportGroup userReportGroup, Guid reportGroupCode)
        {
            userReportGroup.ReportGroupCode = reportGroupCode;
            return userReportGroup;
        }
       	public static UserReportGroup WithAccessLevel(this UserReportGroup userReportGroup, Int32 accessLevel)
        {
            userReportGroup.AccessLevel = accessLevel;
            return userReportGroup;
        }
       	public static UserReportGroup WithReportGroup(this UserReportGroup userReportGroup, ReportGroup reportGroup)
        {
            userReportGroup.ReportGroup = reportGroup;
            return userReportGroup;
        }
    
       	public static UserReportGroup WithUser(this UserReportGroup userReportGroup, MCUser user)
        {
            userReportGroup.User = user;
            return userReportGroup;
        }
    

        #endregion
    }
}
