//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class AlertUser
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual System.Guid AlertCode
        {
            get { return _alertCode; }
            set
            {
                if (_alertCode != value)
                {
                    if (Alert != null && Alert.Code != value)
                    {
                        Alert = null;
                    }
                    _alertCode = value;
                }
            }
        }
        private System.Guid _alertCode;
    
        public virtual System.Guid UserCode
        {
            get { return _userCode; }
            set
            {
                if (_userCode != value)
                {
                    if (User != null && User.Code != value)
                    {
                        User = null;
                    }
                    _userCode = value;
                }
            }
        }
        private System.Guid _userCode;
    
        public virtual string UserMessageStatus
        {
            get;
            set;
        }
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AcknowledgedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Alert Alert
        {
            get { return _alert; }
            set
            {
                if (!ReferenceEquals(_alert, value))
                {
                    var previousValue = _alert;
                    _alert = value;
                    FixupAlert(previousValue);
                }
            }
        }
        private Alert _alert;
    
        public virtual MCUser User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private MCUser _user;

        #endregion
        #region Association Fixup
    
        private void FixupAlert(Alert previousValue)
        {
            if (previousValue != null && previousValue.AlertUsers.Contains(this))
            {
                previousValue.AlertUsers.Remove(this);
            }
    
            if (Alert != null)
            {
                if (!Alert.AlertUsers.Contains(this))
                {
                    Alert.AlertUsers.Add(this);
                }
                if (AlertCode != Alert.Code)
                {
                    AlertCode = Alert.Code;
                }
            }
        }
    
        private void FixupUser(MCUser previousValue)
        {
            if (previousValue != null && previousValue.AlertUsers.Contains(this))
            {
                previousValue.AlertUsers.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.AlertUsers.Contains(this))
                {
                    User.AlertUsers.Add(this);
                }
                if (UserCode != User.Code)
                {
                    UserCode = User.Code;
                }
            }
        }

        #endregion
    }
}
