//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(DataTableJoin.DataTableJoinMetadata))]
    public partial class DataTableJoin : IDataTableJoin
    {
    	public partial class DataTableJoinMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_DataTableRelationshipJoin_DataTableJoin", "Code", "DataTableJoinCode", IsForeignKey = false)]
    		public virtual ICollection<DataTableRelationshipJoin> DataTableRelationshipJoins
    		{get; set;}
    
    		[Include]
    		[Association("FK_ReportDataTableJoin_DataTableJoin", "Code", "DataTableJoinCode", IsForeignKey = false)]
    		public virtual ICollection<ReportDataTableJoin> ReportDataTableJoins
    		{get; set;}
    
    		[Include]
    		[Association("FK_DataTableJoin_DataModel", "DataModelCode", "Code", IsForeignKey = true)]
    		public virtual DataModel DataModel
    		{get; set;}
    
    		}
    }
}
