//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(DataTableRelationship.DataTableRelationshipMetadata))]
    public partial class DataTableRelationship : IDataTableRelationship
    {
    	public partial class DataTableRelationshipMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_DataTableRelationship_DataTable", "DataTableFromCode", "Code", IsForeignKey = true)]
    		public virtual DataTable DataTable
    		{get; set;}
    
    		[Include]
    		[Association("FK_DataTableRelationship_DataTable1", "DataTableToCode", "Code", IsForeignKey = true)]
    		public virtual DataTable DataTable1
    		{get; set;}
    
    		[Include]
    		[Association("FK_DataTableRelationshipJoin_DataTableRelationship", "Code", "DataTableRelationshipCode", IsForeignKey = false)]
    		public virtual ICollection<DataTableRelationshipJoin> DataTableRelationshipJoins
    		{get; set;}
    
    		}
    }
}
