//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class DataTableRelationshipJoin
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual System.Guid DataTableRelationshipCode
        {
            get { return _dataTableRelationshipCode; }
            set
            {
                if (_dataTableRelationshipCode != value)
                {
                    if (DataTableRelationship != null && DataTableRelationship.Code != value)
                    {
                        DataTableRelationship = null;
                    }
                    _dataTableRelationshipCode = value;
                }
            }
        }
        private System.Guid _dataTableRelationshipCode;
    
        public virtual System.Guid DataTableJoinCode
        {
            get { return _dataTableJoinCode; }
            set
            {
                if (_dataTableJoinCode != value)
                {
                    if (DataTableJoin != null && DataTableJoin.Code != value)
                    {
                        DataTableJoin = null;
                    }
                    _dataTableJoinCode = value;
                }
            }
        }
        private System.Guid _dataTableJoinCode;
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual DataTableJoin DataTableJoin
        {
            get { return _dataTableJoin; }
            set
            {
                if (!ReferenceEquals(_dataTableJoin, value))
                {
                    var previousValue = _dataTableJoin;
                    _dataTableJoin = value;
                    FixupDataTableJoin(previousValue);
                }
            }
        }
        private DataTableJoin _dataTableJoin;
    
        public virtual DataTableRelationship DataTableRelationship
        {
            get { return _dataTableRelationship; }
            set
            {
                if (!ReferenceEquals(_dataTableRelationship, value))
                {
                    var previousValue = _dataTableRelationship;
                    _dataTableRelationship = value;
                    FixupDataTableRelationship(previousValue);
                }
            }
        }
        private DataTableRelationship _dataTableRelationship;

        #endregion
        #region Association Fixup
    
        private void FixupDataTableJoin(DataTableJoin previousValue)
        {
            if (previousValue != null && previousValue.DataTableRelationshipJoins.Contains(this))
            {
                previousValue.DataTableRelationshipJoins.Remove(this);
            }
    
            if (DataTableJoin != null)
            {
                if (!DataTableJoin.DataTableRelationshipJoins.Contains(this))
                {
                    DataTableJoin.DataTableRelationshipJoins.Add(this);
                }
                if (DataTableJoinCode != DataTableJoin.Code)
                {
                    DataTableJoinCode = DataTableJoin.Code;
                }
            }
        }
    
        private void FixupDataTableRelationship(DataTableRelationship previousValue)
        {
            if (previousValue != null && previousValue.DataTableRelationshipJoins.Contains(this))
            {
                previousValue.DataTableRelationshipJoins.Remove(this);
            }
    
            if (DataTableRelationship != null)
            {
                if (!DataTableRelationship.DataTableRelationshipJoins.Contains(this))
                {
                    DataTableRelationship.DataTableRelationshipJoins.Add(this);
                }
                if (DataTableRelationshipCode != DataTableRelationship.Code)
                {
                    DataTableRelationshipCode = DataTableRelationship.Code;
                }
            }
        }

        #endregion
    }
}
