//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(DataTable.DataTableMetadata))]
    public partial class DataTable : IDataTable
    {
    	public partial class DataTableMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_DataItem_DataTable", "Code", "DataTableCode", IsForeignKey = false)]
    		public virtual ICollection<DataItem> DataItems
    		{get; set;}
    
    		[Include]
    		[Association("FK_DataTableRelationship_DataTable", "Code", "DataTableFromCode", IsForeignKey = false)]
    		public virtual ICollection<DataTableRelationship> DataTableRelationships
    		{get; set;}
    
    		[Include]
    		[Association("FK_DataTableRelationship_DataTable1", "Code", "DataTableToCode", IsForeignKey = false)]
    		public virtual ICollection<DataTableRelationship> DataTableRelationships1
    		{get; set;}
    
    		[Include]
    		[Association("FK_DataTable_DataModel", "DataModelCode", "Code", IsForeignKey = true)]
    		public virtual DataModel DataModel
    		{get; set;}
    
    		}
    }
}
