//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(DataTableRelationshipJoin.DataTableRelationshipJoinMetadata))]
    public partial class DataTableRelationshipJoin : IDataTableRelationshipJoin
    {
    	public partial class DataTableRelationshipJoinMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_DataTableRelationshipJoin_DataTableJoin", "DataTableJoinCode", "Code", IsForeignKey = true)]
    		public virtual DataTableJoin DataTableJoin
    		{get; set;}
    
    		[Include]
    		[Association("FK_DataTableRelationshipJoin_DataTableRelationship", "DataTableRelationshipCode", "Code", IsForeignKey = true)]
    		public virtual DataTableRelationship DataTableRelationship
    		{get; set;}
    
    		}
    }
}
