//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class DataTableJoin
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual string FromTable
        {
            get;
            set;
        }
    
        public virtual string FromField
        {
            get;
            set;
        }
    
        public virtual string ToTable
        {
            get;
            set;
        }
    
        public virtual string ToField
        {
            get;
            set;
        }
    
        public virtual bool IsOneToOne
        {
            get;
            set;
        }
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }
    
        public virtual string DefaultJoinType
        {
            get;
            set;
        }
    
        public virtual System.Guid DataModelCode
        {
            get { return _dataModelCode; }
            set
            {
                if (_dataModelCode != value)
                {
                    if (DataModel != null && DataModel.Code != value)
                    {
                        DataModel = null;
                    }
                    _dataModelCode = value;
                }
            }
        }
        private System.Guid _dataModelCode;

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<DataTableRelationshipJoin> DataTableRelationshipJoins
        {
            get
            {
                if (_dataTableRelationshipJoins == null)
                {
                    var newCollection = new FixupCollection<DataTableRelationshipJoin>();
                    newCollection.CollectionChanged += FixupDataTableRelationshipJoins;
                    _dataTableRelationshipJoins = newCollection;
                }
                return _dataTableRelationshipJoins;
            }
            set
            {
                if (!ReferenceEquals(_dataTableRelationshipJoins, value))
                {
                    var previousValue = _dataTableRelationshipJoins as FixupCollection<DataTableRelationshipJoin>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupDataTableRelationshipJoins;
                    }
                    _dataTableRelationshipJoins = value;
                    var newValue = value as FixupCollection<DataTableRelationshipJoin>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupDataTableRelationshipJoins;
                    }
                }
            }
        }
        private ICollection<DataTableRelationshipJoin> _dataTableRelationshipJoins;
    
        public virtual ICollection<ReportDataTableJoin> ReportDataTableJoins
        {
            get
            {
                if (_reportDataTableJoins == null)
                {
                    var newCollection = new FixupCollection<ReportDataTableJoin>();
                    newCollection.CollectionChanged += FixupReportDataTableJoins;
                    _reportDataTableJoins = newCollection;
                }
                return _reportDataTableJoins;
            }
            set
            {
                if (!ReferenceEquals(_reportDataTableJoins, value))
                {
                    var previousValue = _reportDataTableJoins as FixupCollection<ReportDataTableJoin>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupReportDataTableJoins;
                    }
                    _reportDataTableJoins = value;
                    var newValue = value as FixupCollection<ReportDataTableJoin>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupReportDataTableJoins;
                    }
                }
            }
        }
        private ICollection<ReportDataTableJoin> _reportDataTableJoins;
    
        public virtual DataModel DataModel
        {
            get { return _dataModel; }
            set
            {
                if (!ReferenceEquals(_dataModel, value))
                {
                    var previousValue = _dataModel;
                    _dataModel = value;
                    FixupDataModel(previousValue);
                }
            }
        }
        private DataModel _dataModel;

        #endregion
        #region Association Fixup
    
        private void FixupDataModel(DataModel previousValue)
        {
            if (previousValue != null && previousValue.DataTableJoins.Contains(this))
            {
                previousValue.DataTableJoins.Remove(this);
            }
    
            if (DataModel != null)
            {
                if (!DataModel.DataTableJoins.Contains(this))
                {
                    DataModel.DataTableJoins.Add(this);
                }
                if (DataModelCode != DataModel.Code)
                {
                    DataModelCode = DataModel.Code;
                }
            }
        }
    
        private void FixupDataTableRelationshipJoins(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (DataTableRelationshipJoin item in e.NewItems)
                {
                    item.DataTableJoin = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (DataTableRelationshipJoin item in e.OldItems)
                {
                    if (ReferenceEquals(item.DataTableJoin, this))
                    {
                        item.DataTableJoin = null;
                    }
                }
            }
        }
    
        private void FixupReportDataTableJoins(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ReportDataTableJoin item in e.NewItems)
                {
                    item.DataTableJoin = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ReportDataTableJoin item in e.OldItems)
                {
                    if (ReferenceEquals(item.DataTableJoin, this))
                    {
                        item.DataTableJoin = null;
                    }
                }
            }
        }

        #endregion
    }
}
