//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(DataItem.DataItemMetadata))]
    public partial class DataItem : IDataItem
    {
    	public partial class DataItemMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_DataItem_DataCategory", "DataCategoryCode", "Code", IsForeignKey = true)]
    		public virtual DataCategory DataCategory
    		{get; set;}
    
    		[Include]
    		[Association("FK_DataItem_DataTable", "DataTableCode", "Code", IsForeignKey = true)]
    		public virtual DataTable DataTable
    		{get; set;}
    
    		[Include]
    		[Association("FK_ReportItem_DataItem", "Code", "DataItemCode", IsForeignKey = false)]
    		public virtual ICollection<ReportItem> ReportItems
    		{get; set;}
    
    		}
    }
}
