//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class DataTable
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }
    
        public virtual System.Guid DataModelCode
        {
            get { return _dataModelCode; }
            set
            {
                if (_dataModelCode != value)
                {
                    if (DataModel != null && DataModel.Code != value)
                    {
                        DataModel = null;
                    }
                    _dataModelCode = value;
                }
            }
        }
        private System.Guid _dataModelCode;
    
        public virtual string SchemaName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<DataItem> DataItems
        {
            get
            {
                if (_dataItems == null)
                {
                    var newCollection = new FixupCollection<DataItem>();
                    newCollection.CollectionChanged += FixupDataItems;
                    _dataItems = newCollection;
                }
                return _dataItems;
            }
            set
            {
                if (!ReferenceEquals(_dataItems, value))
                {
                    var previousValue = _dataItems as FixupCollection<DataItem>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupDataItems;
                    }
                    _dataItems = value;
                    var newValue = value as FixupCollection<DataItem>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupDataItems;
                    }
                }
            }
        }
        private ICollection<DataItem> _dataItems;
    
        public virtual ICollection<DataTableRelationship> DataTableRelationships
        {
            get
            {
                if (_dataTableRelationships == null)
                {
                    var newCollection = new FixupCollection<DataTableRelationship>();
                    newCollection.CollectionChanged += FixupDataTableRelationships;
                    _dataTableRelationships = newCollection;
                }
                return _dataTableRelationships;
            }
            set
            {
                if (!ReferenceEquals(_dataTableRelationships, value))
                {
                    var previousValue = _dataTableRelationships as FixupCollection<DataTableRelationship>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupDataTableRelationships;
                    }
                    _dataTableRelationships = value;
                    var newValue = value as FixupCollection<DataTableRelationship>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupDataTableRelationships;
                    }
                }
            }
        }
        private ICollection<DataTableRelationship> _dataTableRelationships;
    
        public virtual ICollection<DataTableRelationship> DataTableRelationships1
        {
            get
            {
                if (_dataTableRelationships1 == null)
                {
                    var newCollection = new FixupCollection<DataTableRelationship>();
                    newCollection.CollectionChanged += FixupDataTableRelationships1;
                    _dataTableRelationships1 = newCollection;
                }
                return _dataTableRelationships1;
            }
            set
            {
                if (!ReferenceEquals(_dataTableRelationships1, value))
                {
                    var previousValue = _dataTableRelationships1 as FixupCollection<DataTableRelationship>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupDataTableRelationships1;
                    }
                    _dataTableRelationships1 = value;
                    var newValue = value as FixupCollection<DataTableRelationship>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupDataTableRelationships1;
                    }
                }
            }
        }
        private ICollection<DataTableRelationship> _dataTableRelationships1;
    
        public virtual DataModel DataModel
        {
            get { return _dataModel; }
            set
            {
                if (!ReferenceEquals(_dataModel, value))
                {
                    var previousValue = _dataModel;
                    _dataModel = value;
                    FixupDataModel(previousValue);
                }
            }
        }
        private DataModel _dataModel;

        #endregion
        #region Association Fixup
    
        private void FixupDataModel(DataModel previousValue)
        {
            if (previousValue != null && previousValue.DataTables.Contains(this))
            {
                previousValue.DataTables.Remove(this);
            }
    
            if (DataModel != null)
            {
                if (!DataModel.DataTables.Contains(this))
                {
                    DataModel.DataTables.Add(this);
                }
                if (DataModelCode != DataModel.Code)
                {
                    DataModelCode = DataModel.Code;
                }
            }
        }
    
        private void FixupDataItems(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (DataItem item in e.NewItems)
                {
                    item.DataTable = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (DataItem item in e.OldItems)
                {
                    if (ReferenceEquals(item.DataTable, this))
                    {
                        item.DataTable = null;
                    }
                }
            }
        }
    
        private void FixupDataTableRelationships(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (DataTableRelationship item in e.NewItems)
                {
                    item.DataTable = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (DataTableRelationship item in e.OldItems)
                {
                    if (ReferenceEquals(item.DataTable, this))
                    {
                        item.DataTable = null;
                    }
                }
            }
        }
    
        private void FixupDataTableRelationships1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (DataTableRelationship item in e.NewItems)
                {
                    item.DataTable1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (DataTableRelationship item in e.OldItems)
                {
                    if (ReferenceEquals(item.DataTable1, this))
                    {
                        item.DataTable1 = null;
                    }
                }
            }
        }

        #endregion
    }
}
