//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(DataCategory.DataCategoryMetadata))]
    public partial class DataCategory : IDataCategory
    {
    	public partial class DataCategoryMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_DataItem_DataCategory", "Code", "DataCategoryCode", IsForeignKey = false)]
    		public virtual ICollection<DataItem> DataItems
    		{get; set;}
    
    		[Include]
    		[Association("FK_DataCategory_DataModel", "DataModelCode", "Code", IsForeignKey = true)]
    		public virtual DataModel DataModel
    		{get; set;}
    
    		}
    }
}
