//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class Filter
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual string Operand
        {
            get;
            set;
        }
    
        public virtual string FilterValue
        {
            get;
            set;
        }
    
        public virtual System.Guid ReportItemCode
        {
            get { return _reportItemCode; }
            set
            {
                if (_reportItemCode != value)
                {
                    if (ReportItem != null && ReportItem.Code != value)
                    {
                        ReportItem = null;
                    }
                    _reportItemCode = value;
                }
            }
        }
        private System.Guid _reportItemCode;
    
        public virtual int SortField
        {
            get;
            set;
        }
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ReportItem ReportItem
        {
            get { return _reportItem; }
            set
            {
                if (!ReferenceEquals(_reportItem, value))
                {
                    var previousValue = _reportItem;
                    _reportItem = value;
                    FixupReportItem(previousValue);
                }
            }
        }
        private ReportItem _reportItem;

        #endregion
        #region Association Fixup
    
        private void FixupReportItem(ReportItem previousValue)
        {
            if (previousValue != null && previousValue.Filters.Contains(this))
            {
                previousValue.Filters.Remove(this);
            }
    
            if (ReportItem != null)
            {
                if (!ReportItem.Filters.Contains(this))
                {
                    ReportItem.Filters.Add(this);
                }
                if (ReportItemCode != ReportItem.Code)
                {
                    ReportItemCode = ReportItem.Code;
                }
            }
        }

        #endregion
    }
}
