//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(InputFileHistory.InputFileHistoryMetadata))]
    public partial class InputFileHistory : IInputFileHistory
    {
    	public partial class InputFileHistoryMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_InputFileErrors_InputFileHistory", "Code", "InputFileHistoryCode", IsForeignKey = false)]
    		public virtual ICollection<InputFileError> InputFileErrors
    		{get; set;}
    
    		[Include]
    		[Association("FK_ProviderOrganisation_InputFileHistory", "Code", "CurrentValidatedFileCode", IsForeignKey = false)]
    		public virtual ICollection<ProviderOrganisation> ProviderOrganisations
    		{get; set;}
    
    		[Include]
    		[Association("FK_UploadMonitor_InputFileHistory", "Code", "InputFileCode", IsForeignKey = false)]
    		public virtual ICollection<UploadMonitor> UploadMonitors
    		{get; set;}
    
    		}
    }
}
