//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class InputFileError
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual string ErrorMessage
        {
            get;
            set;
        }
    
        public virtual System.Guid InputFileHistoryCode
        {
            get { return _inputFileHistoryCode; }
            set
            {
                if (_inputFileHistoryCode != value)
                {
                    if (InputFileHistory != null && InputFileHistory.Code != value)
                    {
                        InputFileHistory = null;
                    }
                    _inputFileHistoryCode = value;
                }
            }
        }
        private System.Guid _inputFileHistoryCode;
    
        public virtual string RecordKey
        {
            get;
            set;
        }
    
        public virtual string Category
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ErrorLevel
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> RecordDateTime
        {
            get;
            set;
        }
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual InputFileHistory InputFileHistory
        {
            get { return _inputFileHistory; }
            set
            {
                if (!ReferenceEquals(_inputFileHistory, value))
                {
                    var previousValue = _inputFileHistory;
                    _inputFileHistory = value;
                    FixupInputFileHistory(previousValue);
                }
            }
        }
        private InputFileHistory _inputFileHistory;

        #endregion
        #region Association Fixup
    
        private void FixupInputFileHistory(InputFileHistory previousValue)
        {
            if (previousValue != null && previousValue.InputFileErrors.Contains(this))
            {
                previousValue.InputFileErrors.Remove(this);
            }
    
            if (InputFileHistory != null)
            {
                if (!InputFileHistory.InputFileErrors.Contains(this))
                {
                    InputFileHistory.InputFileErrors.Add(this);
                }
                if (InputFileHistoryCode != InputFileHistory.Code)
                {
                    InputFileHistoryCode = InputFileHistory.Code;
                }
            }
        }

        #endregion
    }
}
