//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(InputFileError.InputFileErrorMetadata))]
    public partial class InputFileError : IInputFileError
    {
    	public partial class InputFileErrorMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Key]
    		public System.Guid InputFileHistoryCode{get; set;}
    		[Include]
    		[Association("FK_InputFileErrors_InputFileHistory", "InputFileHistoryCode", "Code", IsForeignKey = true)]
    		public virtual InputFileHistory InputFileHistory
    		{get; set;}
    
    		}
    }
}
