//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class JobStep
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> StartTime
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> EndTime
        {
            get;
            set;
        }
    
        public virtual string Status
        {
            get;
            set;
        }
    
        public virtual string Category
        {
            get;
            set;
        }
    
        public virtual string LogText
        {
            get;
            set;
        }
    
        public virtual System.Guid UploadJobQueueCode
        {
            get { return _uploadJobQueueCode; }
            set
            {
                if (_uploadJobQueueCode != value)
                {
                    if (UploadJobQueue != null && UploadJobQueue.Code != value)
                    {
                        UploadJobQueue = null;
                    }
                    _uploadJobQueueCode = value;
                }
            }
        }
        private System.Guid _uploadJobQueueCode;
    
        public virtual int StepOrder
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual UploadJobQueue UploadJobQueue
        {
            get { return _uploadJobQueue; }
            set
            {
                if (!ReferenceEquals(_uploadJobQueue, value))
                {
                    var previousValue = _uploadJobQueue;
                    _uploadJobQueue = value;
                    FixupUploadJobQueue(previousValue);
                }
            }
        }
        private UploadJobQueue _uploadJobQueue;

        #endregion
        #region Association Fixup
    
        private void FixupUploadJobQueue(UploadJobQueue previousValue)
        {
            if (previousValue != null && previousValue.JobSteps.Contains(this))
            {
                previousValue.JobSteps.Remove(this);
            }
    
            if (UploadJobQueue != null)
            {
                if (!UploadJobQueue.JobSteps.Contains(this))
                {
                    UploadJobQueue.JobSteps.Add(this);
                }
                if (UploadJobQueueCode != UploadJobQueue.Code)
                {
                    UploadJobQueueCode = UploadJobQueue.Code;
                }
            }
        }

        #endregion
    }
}
