//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(MCRole.MCRoleMetadata))]
    public partial class MCRole : IMCRole
    {
    	public partial class MCRoleMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_UserRole_Role", "Code", "RoleCode", IsForeignKey = false)]
    		public virtual ICollection<MCUserRole> UserRoles
    		{get; set;}
    
    		}
    }
}
