//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class MCUserRole
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual System.Guid UserCode
        {
            get { return _userCode; }
            set
            {
                if (_userCode != value)
                {
                    if (User != null && User.Code != value)
                    {
                        User = null;
                    }
                    _userCode = value;
                }
            }
        }
        private System.Guid _userCode;
    
        public virtual System.Guid RoleCode
        {
            get { return _roleCode; }
            set
            {
                if (_roleCode != value)
                {
                    if (Role != null && Role.Code != value)
                    {
                        Role = null;
                    }
                    _roleCode = value;
                }
            }
        }
        private System.Guid _roleCode;
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual MCRole Role
        {
            get { return _role; }
            set
            {
                if (!ReferenceEquals(_role, value))
                {
                    var previousValue = _role;
                    _role = value;
                    FixupRole(previousValue);
                }
            }
        }
        private MCRole _role;
    
        public virtual MCUser User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private MCUser _user;

        #endregion
        #region Association Fixup
    
        private void FixupRole(MCRole previousValue)
        {
            if (previousValue != null && previousValue.UserRoles.Contains(this))
            {
                previousValue.UserRoles.Remove(this);
            }
    
            if (Role != null)
            {
                if (!Role.UserRoles.Contains(this))
                {
                    Role.UserRoles.Add(this);
                }
                if (RoleCode != Role.Code)
                {
                    RoleCode = Role.Code;
                }
            }
        }
    
        private void FixupUser(MCUser previousValue)
        {
            if (previousValue != null && previousValue.UserRoles.Contains(this))
            {
                previousValue.UserRoles.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.UserRoles.Contains(this))
                {
                    User.UserRoles.Add(this);
                }
                if (UserCode != User.Code)
                {
                    UserCode = User.Code;
                }
            }
        }

        #endregion
    }
}
