//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(MCUser.MCUserMetadata))]
    public partial class MCUser : IMCUser
    {
    	public partial class MCUserMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_UserRole_User", "Code", "UserCode", IsForeignKey = false)]
    		public virtual ICollection<MCUserRole> UserRoles
    		{get; set;}
    
    		[Include]
    		[Association("FK_UserReportGroup_User", "Code", "UserCode", IsForeignKey = false)]
    		public virtual ICollection<UserReportGroup> UserReportGroups
    		{get; set;}
    
    		[Include]
    		[Association("FK_AlertUser_User", "Code", "UserCode", IsForeignKey = false)]
    		public virtual ICollection<AlertUser> AlertUsers
    		{get; set;}
    
    		}
    }
}
