//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class ProviderOrganisation
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string RegionID
        {
            get;
            set;
        }
    
        public virtual string KeyValue
        {
            get;
            set;
        }
    
        public virtual string FileType
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Status
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> CurrentValidatedFileCode
        {
            get { return _currentValidatedFileCode; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_currentValidatedFileCode != value)
                    {
                        if (InputFileHistory != null && InputFileHistory.Code != value)
                        {
                            InputFileHistory = null;
                        }
                        _currentValidatedFileCode = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<System.Guid> _currentValidatedFileCode;
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual InputFileHistory InputFileHistory
        {
            get { return _inputFileHistory; }
            set
            {
                if (!ReferenceEquals(_inputFileHistory, value))
                {
                    var previousValue = _inputFileHistory;
                    _inputFileHistory = value;
                    FixupInputFileHistory(previousValue);
                }
            }
        }
        private InputFileHistory _inputFileHistory;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupInputFileHistory(InputFileHistory previousValue)
        {
            if (previousValue != null && previousValue.ProviderOrganisations.Contains(this))
            {
                previousValue.ProviderOrganisations.Remove(this);
            }
    
            if (InputFileHistory != null)
            {
                if (!InputFileHistory.ProviderOrganisations.Contains(this))
                {
                    InputFileHistory.ProviderOrganisations.Add(this);
                }
                if (CurrentValidatedFileCode != InputFileHistory.Code)
                {
                    CurrentValidatedFileCode = InputFileHistory.Code;
                }
            }
            else if (!_settingFK)
            {
                CurrentValidatedFileCode = null;
            }
        }

        #endregion
    }
}
