//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class ReportDBLoadHistory
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual string ReportDBLoadNumber
        {
            get;
            set;
        }
    
        public virtual System.DateTime ReportDBLoadStartTime
        {
            get;
            set;
        }
    
        public virtual string ReportDBLoadTriggeredBy
        {
            get;
            set;
        }
    
        public virtual string ReportDBLoadStatus
        {
            get;
            set;
        }
    
        public virtual System.DateTime ReportDBLoadEndTime
        {
            get;
            set;
        }
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }

        #endregion
    }
}
