//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(ReportChartSery.ReportChartSeryMetadata))]
    public partial class ReportChartSery : IReportChartSery
    {
    	public partial class ReportChartSeryMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_ReportChartSeries_ReportChart", "ReportChartCode", "Code", IsForeignKey = true)]
    		public virtual ReportChart ReportChart
    		{get; set;}
    
    		[Include]
    		[Association("FK_ReportChartSeries_ReportItem", "SeriesReportItemCode", "Code", IsForeignKey = true)]
    		public virtual ReportItem ReportItem
    		{get; set;}
    
    		}
    }
}
