//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(ReportItem.ReportItemMetadata))]
    public partial class ReportItem : IReportItem
    {
    	public partial class ReportItemMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_ReportItem_DataItem", "DataItemCode", "Code", IsForeignKey = true)]
    		public virtual DataItem DataItem
    		{get; set;}
    
    		[Include]
    		[Association("FK_Filter_ReportItem", "Code", "ReportItemCode", IsForeignKey = false)]
    		public virtual ICollection<Filter> Filters
    		{get; set;}
    
    		[Include]
    		[Association("FK_ReportItem_Report", "ReportCode", "Code", IsForeignKey = true)]
    		public virtual Report Report
    		{get; set;}
    
    		[Include]
    		[Association("FK_ReportChart_ReportItem", "Code", "CategoryReportItemCode", IsForeignKey = false)]
    		public virtual ICollection<ReportChart> ReportCharts
    		{get; set;}
    
    		[Include]
    		[Association("FK_ReportChartSeries_ReportItem", "Code", "SeriesReportItemCode", IsForeignKey = false)]
    		public virtual ICollection<ReportChartSery> ReportChartSeries
    		{get; set;}
    
    		}
    }
}
