//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(ReportGroup.ReportGroupMetadata))]
    public partial class ReportGroup : IReportGroup
    {
    	public partial class ReportGroupMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_Report_ReportGroup", "Code", "GroupCode", IsForeignKey = false)]
    		public virtual ICollection<Report> Reports
    		{get; set;}
    
    		[Include]
    		[Association("FK_UserReportGroup_ReportGroup", "Code", "ReportGroupCode", IsForeignKey = false)]
    		public virtual ICollection<UserReportGroup> UserReportGroups
    		{get; set;}
    
    		}
    }
}
