//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(ReportChart.ReportChartMetadata))]
    public partial class ReportChart : IReportChart
    {
    	public partial class ReportChartMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_ReportChart_Report", "ReportCode", "Code", IsForeignKey = true)]
    		public virtual Report Report
    		{get; set;}
    
    		[Include]
    		[Association("FK_ReportChart_ReportItem", "CategoryReportItemCode", "Code", IsForeignKey = true)]
    		public virtual ReportItem ReportItem
    		{get; set;}
    
    		[Include]
    		[Association("FK_ReportChartSeries_ReportChart", "Code", "ReportChartCode", IsForeignKey = false)]
    		public virtual ICollection<ReportChartSery> ReportChartSeries
    		{get; set;}
    
    		}
    }
}
