//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class ReportDB
    {
        #region Primitive Properties
    
        public virtual int ReportDBKey
        {
            get;
            set;
        }
    
        public virtual string ReportDBStatus
        {
            get;
            set;
        }
    
        public virtual System.DateTime ReportDBLastLoadStarted
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ReportDBLastLoadFinished
        {
            get;
            set;
        }
    
        public virtual int ReportDBLoadCounter
        {
            get;
            set;
        }
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }

        #endregion
    }
}
