//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class ReportDataTableJoin
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual string JoinType
        {
            get;
            set;
        }
    
        public virtual System.Guid ReportCode
        {
            get { return _reportCode; }
            set
            {
                if (_reportCode != value)
                {
                    if (Report != null && Report.Code != value)
                    {
                        Report = null;
                    }
                    _reportCode = value;
                }
            }
        }
        private System.Guid _reportCode;
    
        public virtual System.Guid DataTableJoinCode
        {
            get { return _dataTableJoinCode; }
            set
            {
                if (_dataTableJoinCode != value)
                {
                    if (DataTableJoin != null && DataTableJoin.Code != value)
                    {
                        DataTableJoin = null;
                    }
                    _dataTableJoinCode = value;
                }
            }
        }
        private System.Guid _dataTableJoinCode;
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual DataTableJoin DataTableJoin
        {
            get { return _dataTableJoin; }
            set
            {
                if (!ReferenceEquals(_dataTableJoin, value))
                {
                    var previousValue = _dataTableJoin;
                    _dataTableJoin = value;
                    FixupDataTableJoin(previousValue);
                }
            }
        }
        private DataTableJoin _dataTableJoin;
    
        public virtual Report Report
        {
            get { return _report; }
            set
            {
                if (!ReferenceEquals(_report, value))
                {
                    var previousValue = _report;
                    _report = value;
                    FixupReport(previousValue);
                }
            }
        }
        private Report _report;

        #endregion
        #region Association Fixup
    
        private void FixupDataTableJoin(DataTableJoin previousValue)
        {
            if (previousValue != null && previousValue.ReportDataTableJoins.Contains(this))
            {
                previousValue.ReportDataTableJoins.Remove(this);
            }
    
            if (DataTableJoin != null)
            {
                if (!DataTableJoin.ReportDataTableJoins.Contains(this))
                {
                    DataTableJoin.ReportDataTableJoins.Add(this);
                }
                if (DataTableJoinCode != DataTableJoin.Code)
                {
                    DataTableJoinCode = DataTableJoin.Code;
                }
            }
        }
    
        private void FixupReport(Report previousValue)
        {
            if (previousValue != null && previousValue.ReportDataTableJoins.Contains(this))
            {
                previousValue.ReportDataTableJoins.Remove(this);
            }
    
            if (Report != null)
            {
                if (!Report.ReportDataTableJoins.Contains(this))
                {
                    Report.ReportDataTableJoins.Add(this);
                }
                if (ReportCode != Report.Code)
                {
                    ReportCode = Report.Code;
                }
            }
        }

        #endregion
    }
}
