//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(Report.ReportMetadata))]
    public partial class Report : IReport
    {
    	public partial class ReportMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_Report_ReportGroup", "GroupCode", "Code", IsForeignKey = true)]
    		public virtual ReportGroup ReportGroup
    		{get; set;}
    
    		[Include]
    		[Association("FK_ReportItem_Report", "Code", "ReportCode", IsForeignKey = false)]
    		public virtual ICollection<ReportItem> ReportItems
    		{get; set;}
    
    		[Include]
    		[Association("FK_ReportDataTableJoin_Report", "Code", "ReportCode", IsForeignKey = false)]
    		public virtual ICollection<ReportDataTableJoin> ReportDataTableJoins
    		{get; set;}
    
    		[Include]
    		[Association("FK_ReportChart_Report", "Code", "ReportCode", IsForeignKey = false)]
    		public virtual ICollection<ReportChart> ReportCharts
    		{get; set;}
    
    		[Include]
    		[Association("FK_Report_DataModel1", "DataModelCode", "Code", IsForeignKey = true)]
    		public virtual DataModel DataModel_1
    		{get; set;}
    
    		}
    }
}
