//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace UcbManagementInformation.Server.DataAccess
{
    public interface IUcbManagementInformationEntities : IDisposable, IObjectContext
    {
        #region ObjectSet Properties
        IObjectSet<DataCategory> DataCategories {get;}
        IObjectSet<DataItem> DataItems {get;}
        IObjectSet<DataTable> DataTables {get;}
        IObjectSet<DataTableJoin> DataTableJoins {get;}
        IObjectSet<DataTableRelationship> DataTableRelationships {get;}
        IObjectSet<DataTableRelationshipJoin> DataTableRelationshipJoins {get;}
        IObjectSet<DataModel> DataModels {get;}
        IObjectSet<Filter> Filters {get;}
        IObjectSet<Report> Reports {get;}
        IObjectSet<ReportGroup> ReportGroups {get;}
        IObjectSet<ReportItem> ReportItems {get;}
        IObjectSet<MCRole> MCRoles {get;}
        IObjectSet<MCUser> MCUsers {get;}
        IObjectSet<MCUserRole> MCUserRoles {get;}
        IObjectSet<UserReportGroup> UserReportGroups {get;}
        IObjectSet<ReportDataTableJoin> ReportDataTableJoins {get;}
        IObjectSet<ReportChart> ReportCharts {get;}
        IObjectSet<ReportChartSery> ReportChartSeries {get;}
        IObjectSet<Category> Categories {get;}
        IObjectSet<CategoryLog> CategoryLogs {get;}
        IObjectSet<InputFileError> InputFileErrors {get;}
        IObjectSet<InputFileHistory> InputFileHistories {get;}
        IObjectSet<Log> Logs {get;}
        IObjectSet<ProviderOrganisation> ProviderOrganisations {get;}
        IObjectSet<UploadJobQueue> UploadJobQueues {get;}
        IObjectSet<UploadMonitor> UploadMonitors {get;}
        IObjectSet<ReportDB> ReportDBs {get;}
        IObjectSet<ReportDBLoadHistory> ReportDBLoadHistories {get;}
        IObjectSet<JobStep> JobSteps {get;}
        IObjectSet<Alert> Alerts {get;}
        IObjectSet<AlertUser> AlertUsers {get;}
        IObjectSet<MCSystemParameter> MCSystemParameters {get;}

        #endregion
        #region Function Imports
        ObjectResult<string> GetReferenceData(string dataTableName, string dataFieldName, string dataSourceName) ;
        ObjectResult<string> GetReferenceData1(string dataTableName, string dataTableSchemaName, string dataFieldName, string dataSourceName, string startsWith, string userCode) ;

        #endregion
    }
}
