//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(UploadJobQueue.UploadJobQueueMetadata))]
    public partial class UploadJobQueue : IUploadJobQueue
    {
    	public partial class UploadJobQueueMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_JobStep_UploadJobQueue", "Code", "UploadJobQueueCode", IsForeignKey = false)]
    		public virtual ICollection<JobStep> JobSteps
    		{get; set;}
    
    		}
    }
}
