//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class UploadMonitor
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual int Position
        {
            get;
            set;
        }
    
        public virtual System.Guid InputFileCode
        {
            get { return _inputFileCode; }
            set
            {
                if (_inputFileCode != value)
                {
                    if (InputFileHistory != null && InputFileHistory.Code != value)
                    {
                        InputFileHistory = null;
                    }
                    _inputFileCode = value;
                }
            }
        }
        private System.Guid _inputFileCode;
    
        public virtual System.DateTime TimeOccured
        {
            get;
            set;
        }
    
        public virtual string StepDescription
        {
            get;
            set;
        }
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual InputFileHistory InputFileHistory
        {
            get { return _inputFileHistory; }
            set
            {
                if (!ReferenceEquals(_inputFileHistory, value))
                {
                    var previousValue = _inputFileHistory;
                    _inputFileHistory = value;
                    FixupInputFileHistory(previousValue);
                }
            }
        }
        private InputFileHistory _inputFileHistory;

        #endregion
        #region Association Fixup
    
        private void FixupInputFileHistory(InputFileHistory previousValue)
        {
            if (previousValue != null && previousValue.UploadMonitors.Contains(this))
            {
                previousValue.UploadMonitors.Remove(this);
            }
    
            if (InputFileHistory != null)
            {
                if (!InputFileHistory.UploadMonitors.Contains(this))
                {
                    InputFileHistory.UploadMonitors.Add(this);
                }
                if (InputFileCode != InputFileHistory.Code)
                {
                    InputFileCode = InputFileHistory.Code;
                }
            }
        }

        #endregion
    }
}
