//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class UserReportGroup
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual System.Guid UserCode
        {
            get { return _userCode; }
            set
            {
                if (_userCode != value)
                {
                    if (User != null && User.Code != value)
                    {
                        User = null;
                    }
                    _userCode = value;
                }
            }
        }
        private System.Guid _userCode;
    
        public virtual System.Guid ReportGroupCode
        {
            get { return _reportGroupCode; }
            set
            {
                if (_reportGroupCode != value)
                {
                    if (ReportGroup != null && ReportGroup.Code != value)
                    {
                        ReportGroup = null;
                    }
                    _reportGroupCode = value;
                }
            }
        }
        private System.Guid _reportGroupCode;
    
        public virtual int AccessLevel
        {
            get;
            set;
        }
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ReportGroup ReportGroup
        {
            get { return _reportGroup; }
            set
            {
                if (!ReferenceEquals(_reportGroup, value))
                {
                    var previousValue = _reportGroup;
                    _reportGroup = value;
                    FixupReportGroup(previousValue);
                }
            }
        }
        private ReportGroup _reportGroup;
    
        public virtual MCUser User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private MCUser _user;

        #endregion
        #region Association Fixup
    
        private void FixupReportGroup(ReportGroup previousValue)
        {
            if (previousValue != null && previousValue.UserReportGroups.Contains(this))
            {
                previousValue.UserReportGroups.Remove(this);
            }
    
            if (ReportGroup != null)
            {
                if (!ReportGroup.UserReportGroups.Contains(this))
                {
                    ReportGroup.UserReportGroups.Add(this);
                }
                if (ReportGroupCode != ReportGroup.Code)
                {
                    ReportGroupCode = ReportGroup.Code;
                }
            }
        }
    
        private void FixupUser(MCUser previousValue)
        {
            if (previousValue != null && previousValue.UserReportGroups.Contains(this))
            {
                previousValue.UserReportGroups.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.UserReportGroups.Contains(this))
                {
                    User.UserReportGroups.Add(this);
                }
                if (UserCode != User.Code)
                {
                    UserCode = User.Code;
                }
            }
        }

        #endregion
    }
}
