//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(UserReportGroup.UserReportGroupMetadata))]
    public partial class UserReportGroup : IUserReportGroup
    {
    	public partial class UserReportGroupMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_UserReportGroup_ReportGroup", "ReportGroupCode", "Code", IsForeignKey = true)]
    		public virtual ReportGroup ReportGroup
    		{get; set;}
    
    		[Include]
    		[Association("FK_UserReportGroup_User", "UserCode", "Code", IsForeignKey = true)]
    		public virtual MCUser User
    		{get; set;}
    
    		}
    }
}
