//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(ApplicationAttribute.ApplicationAttributeMetadata))]
    public partial class ApplicationAttribute : IApplicationAttribute
    {
    	public partial class ApplicationAttributeMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_ApplicationAttribute_Application", "ApplicationCode", "Code", IsForeignKey = true)]
    		public virtual Application Application
    		{get; set;}
    
    		[Include]
    		[Association("FK_StaffAttributes_ApplicationAttribute", "Code", "ApplicationAttributeCode", IsForeignKey = false)]
    		public virtual ICollection<StaffAttribute> StaffAttributes
    		{get; set;}
    
    		}
    }
}
