//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class ReportCategory
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<StandardReport> StandardReports
        {
            get
            {
                if (_standardReports == null)
                {
                    var newCollection = new FixupCollection<StandardReport>();
                    newCollection.CollectionChanged += FixupStandardReports;
                    _standardReports = newCollection;
                }
                return _standardReports;
            }
            set
            {
                if (!ReferenceEquals(_standardReports, value))
                {
                    var previousValue = _standardReports as FixupCollection<StandardReport>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupStandardReports;
                    }
                    _standardReports = value;
                    var newValue = value as FixupCollection<StandardReport>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupStandardReports;
                    }
                }
            }
        }
        private ICollection<StandardReport> _standardReports;

        #endregion
        #region Association Fixup
    
        private void FixupStandardReports(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (StandardReport item in e.NewItems)
                {
                    item.ReportCategory = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (StandardReport item in e.OldItems)
                {
                    if (ReferenceEquals(item.ReportCategory, this))
                    {
                        item.ReportCategory = null;
                    }
                }
            }
        }

        #endregion
    }
}
