//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(ReportCategory.ReportCategoryMetadata))]
    public partial class ReportCategory : IReportCategory
    {
    	public partial class ReportCategoryMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_StandardReport_ReportCategory", "Code", "ReportCategoryCode", IsForeignKey = false)]
    		public virtual ICollection<StandardReport> StandardReports
    		{get; set;}
    
    		}
    }
}
