//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel.DomainServices.Server;

namespace UcbManagementInformation.Server.DataAccess
{
    [MetadataTypeAttribute(typeof(StaffAttribute.StaffAttributeMetadata))]
    public partial class StaffAttribute : IStaffAttribute
    {
    	public partial class StaffAttributeMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    		[Include]
    		[Association("FK_StaffAttributes_Staff", "StaffCode", "Code", IsForeignKey = true)]
    		public virtual Staff Staff
    		{get; set;}
    
    		[Include]
    		[Association("FK_StaffAttributes_Application", "ApplicationCode", "Code", IsForeignKey = true)]
    		public virtual Application Application
    		{get; set;}
    
    		[Include]
    		[Association("FK_StaffAttributes_ApplicationAttribute", "ApplicationAttributeCode", "Code", IsForeignKey = true)]
    		public virtual ApplicationAttribute ApplicationAttribute
    		{get; set;}
    
    		}
    }
}
