//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace UcbManagementInformation.Server.DataAccess
{
    public partial class AdepUcbEntities : ObjectContext, IAdepUcbEntities
    {
        public const string ConnectionString = "name=AdepUcbEntities";
        public const string ContainerName = "AdepUcbEntities";
    
        #region Constructors
    
        public AdepUcbEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public AdepUcbEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public AdepUcbEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public IObjectSet<Staff> Staffs
        {
            get { return _staffs  ?? (_staffs = CreateObjectSet<Staff>("Staffs")); }
        }
        private ObjectSet<Staff> _staffs;
    
        public IObjectSet<StaffAttribute> StaffAttributes
        {
            get { return _staffAttributes  ?? (_staffAttributes = CreateObjectSet<StaffAttribute>("StaffAttributes")); }
        }
        private ObjectSet<StaffAttribute> _staffAttributes;
    
        public IObjectSet<Application> Applications
        {
            get { return _applications  ?? (_applications = CreateObjectSet<Application>("Applications")); }
        }
        private ObjectSet<Application> _applications;
    
        public IObjectSet<ApplicationAttribute> ApplicationAttributes
        {
            get { return _applicationAttributes  ?? (_applicationAttributes = CreateObjectSet<ApplicationAttribute>("ApplicationAttributes")); }
        }
        private ObjectSet<ApplicationAttribute> _applicationAttributes;
    
        public IObjectSet<ReportCategory> ReportCategories
        {
            get { return _reportCategories  ?? (_reportCategories = CreateObjectSet<ReportCategory>("ReportCategories")); }
        }
        private ObjectSet<ReportCategory> _reportCategories;
    
        public IObjectSet<StandardReport> StandardReports
        {
            get { return _standardReports  ?? (_standardReports = CreateObjectSet<StandardReport>("StandardReports")); }
        }
        private ObjectSet<StandardReport> _standardReports;

        #endregion
    }
}
