//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace UcbManagementInformation.Server.DataAccess
{
    public interface IAdepUcbEntities : IDisposable, IObjectContext
    {
        #region ObjectSet Properties
        IObjectSet<Staff> Staffs {get;}
        IObjectSet<StaffAttribute> StaffAttributes {get;}
        IObjectSet<Application> Applications {get;}
        IObjectSet<ApplicationAttribute> ApplicationAttributes {get;}
        IObjectSet<ReportCategory> ReportCategories {get;}
        IObjectSet<StandardReport> StandardReports {get;}

        #endregion
    }
}
